logging:
  level:
    ru.m15.ekspring: DEBUG
    org.springframework.web: TRACE


server:
  port: 8102

spring:
  datasource:
    url: jdbc:postgresql://db:5432/ekspg
    username: eku01
    password: tnG4-gr6D
    driver-class-name: org.postgresql.Driver

  flyway:
    baselineOnMigrate: true
    url: jdbc:postgresql://db:5432/ekspg
    user: eku01
    password: tnG4-gr6D
    driver-class-name: org.postgresql.Driver
    locations: classpath:db/migration


# actuator
info:
  app:
    name: First test service
    version: 1.0.0
    description: Test learning service


# do not think about it - just do it

# actuator settings
management:
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info,health,prometheus

