
server:
  port: 8102


# ?????????? ? ??????? ??? actuator
info:
  app:
    name: First test service
    version: 1.0.0
    description: Test learning service


# do not think about it - just do it

# actuator settings
management:
  info:
    env:
      enabled: true
  #  ??????????? health
  endpoint:
    health:
      show-details: always
  #  ????????? ????????? ? ???????
  endpoints:
    web:
      exposure:
        include: info,health,prometheus

