name: ekspring
version: '3.7'

services:

  app:
    build:
      context: ./..
      dockerfile: ./scripts/app/Dockerfile
#    network_mode: host
    container_name: app-container
    ports:
      - "8102:8102"
    extra_hosts:
      - host.docker.internal:host-gateway
      # use host.docker.internal in app.yaml
#    depends_on:
#      db:
#        condition: service_healthy
#    networks:
#      - custom_network

#networks:
#  custom_network:
#    driver: bridge